model:
  checkpoint_path: "outputs/checkpoints/final_model.ckpt"
  input_shape: [1, 3, 224, 224]  # batch_size, channels, height, width
  num_classes: 75

conversion:
  convert_to_onnx: true
  convert_to_tensorrt: false  # Сначала отключим TensorRT

onnx:
  output_path: "outputs/onnx/model.onnx"
  opset_version: 13  # Используем более новую стабильную версию
  dynamic_axes: null  # Отключаем динамические оси для начала

tensorrt:
  output_path: "outputs/tensorrt/model.engine"
  precision: "fp16"  # fp32, fp16, int8
  max_batch_size: 32
  max_workspace_size: 1073741824  # 1GB in bytes
